### ISSUE TITLE
crash on fullscreen rpi4/rk3399 standalone version

### ISSUE THREAD

**Issue by Askmewho** [notaz/pcsx_rearmed#164]
HI! I've tested the same armhf build on both devices and both crash under opengl on fullscreen for the standalone version.
the sdl1 based can't do fullscreen. 

```
pi@raspberrypi:/media/pi/Externo/RASPBERRY/pcsx_rearmed $ gdb ./pcsx
GNU gdb (Raspbian 8.2.1-2) 8.2.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "arm-linux-gnueabihf".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./pcsx...done.
(gdb) run
Starting program: /media/pi/Externo/RASPBERRY/pcsx_rearmed/pcsx 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
plat_sdl: using 1920x1080 as fullscreen resolution
plat_sdl: overlay: fmt 59565955, planes: 1, pitch: 1280, hw: 0
warning: video overlay is not hardware accelerated, not going to use it.
input: new device #0 "sdl:keys"
input: async-only devices detected..
# drv probed binds name
0   0      y     y sdl:keys
found skin.txt
frontend/libpicofe/readpng.c: failed to open: /home/pi/.picodrive/skin/background.png
me_id2offset: id 28 not found
Starting PCSX-ReARMed r22-98-gaa3b787
Running PCSX Version 1.9 (Mar 15 2020).
warning: failed to do hugetlb mmap (0x80000000, 2162688): 22
Init new dynarec
testing if we can run recompiled code..
test passed.
Mapped (RAM/scrp/ROM/LUTs/TC):
80000000/1f800000/1fc00000/08000000/0089a000
Loading memory card ./.pcsx/memcards/card1.mcd
Loading memory card ./.pcsx/memcards/card2.mcd
plugin: plugins/builtin_cdr
plugin: plugins/builtin_gpu
plugin: plugins/builtin_spu
plugin: plugins/builtin_pad
plugin: plugins/builtin_pad
[New Thread 0xb53693b0 (LWP 1432)]
Plugins loaded.
selected sound output driver: oss
ari64_reset
selected file: /media/pi/Externo/ROMS/PSX/Spyro the Dragon (USA).cue
[Thread 0xb53693b0 (LWP 1432) exited]
plugin: plugins/builtin_gpu
plugin: plugins/builtin_spu
plugin: plugins/builtin_pad
plugin: plugins/builtin_pad
[New Thread 0xb53693b0 (LWP 1436)]
Plugins loaded.
Loaded CD Image: /media/pi/Externo/ROMS/PSX/Spyro the Dragon (USA).cue[+cue].
Track 01 (DATA) - Start 00:02:00, Length 62:30:20
selected sound output driver: oss
CD-ROM Label: SPYRO                           
CD-ROM ID: SCUS94228
CD-ROM EXE Name: SCUS_942.28;1
ari64_reset
  -> 640x480 1.3
[New Thread 0xb3ed23b0 (LWP 1439)]
  -> 640x480 1.3
  -> 640x480 1.3
msg: config saved
Loaded CD Image: /media/pi/Externo/ROMS/PSX/Spyro the Dragon (USA).cue[+cue].
Track 01 (DATA) - Start 00:02:00, Length 62:30:20
selected sound output driver: oss
ari64_reset
CD-ROM Label: SPYRO                           
CD-ROM ID: SCUS94228
CD-ROM EXE Name: SCUS_942.28;1
  -> 640x480 1.3
  -> 640x480 1.3
  -> 640x480 1.3
  -> 640x480 1.3
  -> 640x480 1.3

Thread 1 "pcsx" received signal SIGSEGV, Segmentation fault.
bgr555_to_rgb565 () at frontend/cspace_neon.S:47
47	    vstmia      r0!, {q8-q11}
(gdb) bt
#0  bgr555_to_rgb565 () at frontend/cspace_neon.S:47
#1  0x0009e2ec in pl_vout_flip (vram=<optimized out>, stride=16, 
    stride@entry=1024, bgr24=<optimized out>, w=480, h=480)
    at frontend/plugin_lib.c:401
#2  0x000754a0 in vout_update () at plugins/gpulib/vout_pl.c:85
#3  0x00075128 in GPUupdateLace () at plugins/gpulib/gpu.c:696
#4  0x00031fa8 in psxRcntUpdate () at libpcsxcore/psxcounters.c:336
#5  0x0006d090 in irq_test () at libpcsxcore/new_dynarec/emu_if.c:82
#6  0x0006d360 in gen_interupt () at libpcsxcore/new_dynarec/emu_if.c:97
#7  0x0006b6f8 in cc_interrupt () at libpcsxcore/new_dynarec/linkage_arm.S:452
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```

**Comment by Askmewho** [comment]
It was a faulty bios
