### ISSUE TITLE
[HLE] segfault on loading screen with Star Wars Dark Forces

### ISSUE THREAD

**Issue by DrUm78** [notaz/pcsx_rearmed#298]
OS: Ubuntu 20.04
Hardware: x86_64
Software: Latest PCSX ReARMed commit 8987ee208f057b59a35815f4e6a805935faf2fc8
ISO: Star Wars Dark Forces (USA)

segfault occurs in HLE (runs fine in LLE) on the 1st loading screen after the logo sequence with Star Wars Dark Forces (USA). It worked a moment ago, not sure when though, at least several months ago.

gdb stacktrace:
```
Thread 1 "pcsx" received signal SIGSEGV, Segmentation fault.
0x00005555555ced39 in fetchNoCache (memRLUT=0x567138b0, pc=2147969540) at libpcsxcore/psxinterpreter.c:61
61              u8 *base = memRLUT[pc >> 16];
(gdb) bt
#0  0x00005555555ced39 in fetchNoCache (memRLUT=0x567138b0, pc=2147969540) at libpcsxcore/psxinterpreter.c:61
#1  0x00005555555cfd17 in psxBranchNoDelay (regs_=<optimized out>) at libpcsxcore/psxinterpreter.c:405
#2  0x00005555555d0675 in psxDelayBranchTest (tar1=2147969520) at libpcsxcore/psxinterpreter.c:529
#3  doBranch (tar=2147969520) at libpcsxcore/psxinterpreter.c:529
#4  0x00005555555d050d in execI_ (regs_=<optimized out>, memRLUT=0x5555567138b0) at libpcsxcore/psxinterpreter.c:1092
#5  intExecute () at libpcsxcore/psxinterpreter.c:1101
#6  0x00005555555b34a0 in main (argc=<optimized out>, argv=0x7fffffffd758) at frontend/main.c:687
```

Please note that it also happens on the FunKey S handheld (HLE) which has a ARM Cortex A7-A and uses ARM dynarec.

1. Launch Star Wars Dark Forces (USA) in HLE (no bios)
2. Skip the logo sequence to reach the "blue" loading screen
3. Notice the segfault

**Comment by DrUm78** [comment]
Indeed that now works, thanks! 🙏
